# Generated by Django 6.0.2 on 2026-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_restrictions',
            field=models.CharField(blank=True, default='', help_text='Comma-separated: vegan, vegetarian, gluten-free, dairy-free, halal, kosher, …', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='known_allergens',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of allergen names to always highlight, e.g. ["milk","gluten"]'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='nutriscan_user',
        ),
    ]
